"""
This is a setup.py script generated by py2applet

Usage:
    python setup_osx.py py2app
"""

from setuptools import setup

APP = ['mount_filers.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': '/Users/bancal/SWITCHdrive/mount_filers/client/mount_filers.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
